###########################
#
# D W M
#
###########################
#exec feh --bg-scale ~/.wallpapers/earthstarsnebula2mc3.jpg&
#exec xbindkeys&
#exec gnome-screensaver&
#exec ~/.dwm/init.sh&
#exec ~/.dwm/dwm
#
#
###########################
#
# E N L I G H T E N M E N T
#
###########################

exec xbindkeys&
exec gnome-screensaver&
#sleep 2 && exec wbar.mine&
exec ~/.dzen2/rundzen.sh&
exec e16
